[package]
name = "benday-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = {version="1.0.166", features=["derive"]}
ast-node = {git="https://github.com/BendayLang/ast-node"}